#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

data_bag_path 'data_bags'

cookbook 'runit'
cookbook 'apache2', :git => 'git://github.com/sous-chefs/apache2.git'
cookbook 'composer', :git => 'git://github.com/djoos-cookbooks/composer.git'
cookbook 'mariadb', :git => 'git://github.com/sous-chefs/mariadb'
