#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'runit'
cookbook 'apache2', :git => 'git://github.com/sous-chefs/apache2.git'
cookbook 'php', :git => 'git://github.com/chef-cookbooks/php.git'
cookbook 'php-fpm', :git => 'git://github.com/yevgenko/cookbook-php-fpm.git'
cookbook 'composer', :git => 'git://github.com/djoos-cookbooks/composer.git'
cookbook 'mariadb', :git => 'git://github.com/sous-chefs/mariadb'
